server:
   port: 6502
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/ 
   instance:
      appName:OrderServiceLoadBalancer
spring:
   application:
      name: OrderServiceLoadBalancer
resilience4j:
   circuitbreaker:
      configs:
        default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 5s
            slidingWindowType: COUNT_BASED
            failureRateThreshold: 50
            minimumNumberOfCalls: 5